[project]
name = "KazeIPRegion"
version = "0.1.0"
description = "Meow, meow, meow"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddddocr>=1.5.6",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
]
